CREATE TABLE STUDENT
(
  SRN INT NOT NULL,
  BRANCH INT NOT NULL,
  NAME INT NOT NULL,
  EMAIL INT NOT NULL,
  SECTION INT NOT NULL,
  ACC_INFO INT NOT NULL,
  CGPA INT NOT NULL,
  PRIMARY KEY (SRN)
);

CREATE TABLE SCHOLARSHIP
(
  SC_ID INT NOT NULL,
  TYPE INT NOT NULL,
  SEM INT NOT NULL,
  SRN INT NOT NULL,
  PRIMARY KEY (SC_ID),
  FOREIGN KEY (SRN) REFERENCES STUDENT(SRN)
);

CREATE TABLE COURSE
(
  C_NAME INT NOT NULL,
  C_CODE INT NOT NULL,
  DEPT INT NOT NULL,
  CREDITS INT NOT NULL,
  PRIMARY KEY (C_CODE)
);

CREATE TABLE ELECTIVES
(
  E_CODE INT NOT NULL,
  E_NAME INT NOT NULL,
  CREDITS INT NOT NULL,
  DEPT INT NOT NULL,
  PRE_REQ INT NOT NULL,
  PRIMARY KEY (E_CODE)
);

CREATE TABLE ADMIN
(
  ADMIN_ID INT NOT NULL,
  NAME INT NOT NULL,
  PASSWORD INT NOT NULL,
  PRIMARY KEY (ADMIN_ID)
);

CREATE TABLE ANNOUNCEMENTS
(
  BRANCH INT NOT NULL,
  SEM INT NOT NULL,
  ADMIN_ID INT NOT NULL,
  PRIMARY KEY (BRANCH, SEM),
  FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);

CREATE TABLE FEEDBACK_AND_REPLY
(
  QUERY INT NOT NULL,
  REPLY INT NOT NULL,
  SRN INT NOT NULL,
  ADMIN_ID INT NOT NULL,
  FOREIGN KEY (SRN) REFERENCES STUDENT(SRN),
  FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);

CREATE TABLE ROOM
(
  ROOM_NO INT NOT NULL,
  TIME INT NOT NULL,
  C_CODE INT NOT NULL,
  E_CODE INT NOT NULL,
  PRIMARY KEY (ROOM_NO, TIME),
  FOREIGN KEY (C_CODE) REFERENCES COURSE(C_CODE),
  FOREIGN KEY (E_CODE) REFERENCES ELECTIVES(E_CODE)
);

CREATE TABLE EXAM_INFO
(
  E_ID INT NOT NULL,
  TIME INT NOT NULL,
  DATE INT NOT NULL,
  ROOM INT NOT NULL,
  C_CODE INT NOT NULL,
  E_CODE INT NOT NULL,
  PRIMARY KEY (E_ID),
  FOREIGN KEY (C_CODE) REFERENCES COURSE(C_CODE),
  FOREIGN KEY (E_CODE) REFERENCES ELECTIVES(E_CODE)
);

CREATE TABLE TIME_TABLE
(
  DAY INT NOT NULL,
  BRANCH INT NOT NULL,
  SEM INT NOT NULL,
  ROOM_NO INT NOT NULL,
  TIME INT NOT NULL,
  PRIMARY KEY (BRANCH, SEM),
  FOREIGN KEY (ROOM_NO, TIME) REFERENCES ROOM(ROOM_NO, TIME)
);

CREATE TABLE INSTRUCTOR
(
  INSTR_ID INT NOT NULL,
  INSTR_NAME INT NOT NULL,
  ROOM_NO INT NOT NULL,
  TIME INT NOT NULL,
  PRIMARY KEY (INSTR_ID),
  FOREIGN KEY (ROOM_NO, TIME) REFERENCES ROOM(ROOM_NO, TIME)
);

CREATE TABLE RES_ELEC
(
  ISA1 INT NOT NULL,
  ISA2 INT NOT NULL,
  ESA INT NOT NULL,
  SRN INT NOT NULL,
  E_CODE INT NOT NULL,
  FOREIGN KEY (SRN) REFERENCES STUDENT(SRN),
  FOREIGN KEY (E_CODE) REFERENCES ELECTIVES(E_CODE)
);

CREATE TABLE RES_COURSE
(
  ISA1 INT NOT NULL,
  ISA2 INT NOT NULL,
  ESA INT NOT NULL,
  SRN INT NOT NULL,
  C_CODE INT NOT NULL,
  FOREIGN KEY (SRN) REFERENCES STUDENT(SRN),
  FOREIGN KEY (C_CODE) REFERENCES COURSE(C_CODE)
);

CREATE TABLE ST_COURSES
(
  SRN INT NOT NULL,
  C_CODE INT NOT NULL,
  INSTR_ID INT NOT NULL,
  FOREIGN KEY (SRN) REFERENCES STUDENT(SRN),
  FOREIGN KEY (C_CODE) REFERENCES COURSE(C_CODE),
  FOREIGN KEY (INSTR_ID) REFERENCES INSTRUCTOR(INSTR_ID)
);

CREATE TABLE ST_ELECTIVES
(
  SRN INT NOT NULL,
  INSTR_ID INT NOT NULL,
  E_CODE INT NOT NULL,
  FOREIGN KEY (SRN) REFERENCES STUDENT(SRN),
  FOREIGN KEY (INSTR_ID) REFERENCES INSTRUCTOR(INSTR_ID),
  FOREIGN KEY (E_CODE) REFERENCES ELECTIVES(E_CODE)
);

